# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        name: flake8 - Python linting
        args: ["hooks", "tests", "{{ cookiecutter.repo_name }}/src"]
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.1.0
    hooks:
    -   id: detect-secrets
        name: detect-secrets - Detect secrets in staged code
        args: ["--baseline", ".secrets.baseline"]
        exclude: .*/tests/.*
- repo: https://github.com/kynan/nbstripout
  rev: 0.4.0
  hooks:
    - id: nbstripout
      name: nbstripout - Strip outputs from notebooks (auto-fixes)
      args:
        - --extra-keys
        - "metadata.colab metadata.kernelspec cell.metadata.colab cell.metadata.executionInfo cell.metadata.id cell.metadata.outputId"
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
        name: Check for files larger than 5 MB
        args: ["--maxkb=5120"]
    -   id: end-of-file-fixer
        name: Check for a blank line at the end of scripts (auto-fixes)
    -   id: trailing-whitespace
        name: Check for trailing whitespaces (auto-fixes)
-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
    -   id: isort
        name: isort - Sort Python imports (auto-fixes)
        types: [cython, pyi, python]
